before_install:
- openssl aes-256-cbc
  -K $encrypted_71a31e1b077f_key
  -iv $encrypted_71a31e1b077f_iv
  -in conf/travis_ci/google/gdrive/secrets.tar.enc
  -out conf/travis_ci/google/gdrive/secrets.tar
  -d
- pushd conf/travis_ci/google/gdrive && tar xvf secrets.tar && popd
script:
- pwd
- "./gradlew check -Puploader.run.environment=travis_ci --info --no-daemon"
